# Generated by Django 4.2.1 on 2024-01-06 09:16

from django.db import migrations


def update_default_avatar_src(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    profiles_to_update = Profile.objects.filter(avatar='default.png')
    for profile in profiles_to_update:
        profile.avatar = 'avatars/default.png'
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240106_0811'),
    ]

    operations = [
        migrations.RunPython(update_default_avatar_src),
    ]
