# Generated by Django 4.2.1 on 2023-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
