# Generated by Django 4.2.1 on 2024-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todoBoard', '0003_setup_board_and_task_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'permissions': [('can_edit_task', 'Allow user to edit task details'), ('can_delete_task', 'Allow user to delete task'), ('can_create_task', 'Allow user to add task')]},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': [('can_view_board', 'Allow user to view board'), ('can_delete_board', 'Allow user to delete board'), ('can_edit_board', 'Allow user to edit board details')]},
        ),
        migrations.AddField(
            model_name='todolist',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='allowed_boards', to='auth.group'),
        ),
    ]
