# Generated by Django 4.2.1 on 2024-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todoBoard', '0004_alter_todoitem_options_alter_todolist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_boards', to='auth.group'),
        ),
    ]
