# Generated by Django 4.2.1 on 2024-01-14 21:08

from django.db import migrations


def create_board_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    TodoList = apps.get_model('todoBoard', 'TodoList')

    # Fetch TodoList(board) content type
    board_content_type = ContentType.objects.get_for_model(TodoList)

    # Create group
    board_admins, _ = Group.objects.get_or_create(name='Board admins')
    board_editors, _ = Group.objects.get_or_create(name='Board editors')

    # Add permissions
    board_admin_permissions = Permission.objects.filter(content_type=board_content_type)
    board_editor_permissions = Permission.objects.filter(content_type=board_content_type,
                                                         codename__in=['can_view_board', 'can_edit_board'])

    board_admins.permissions.add(*board_admin_permissions)
    board_editors.permissions.add(*board_editor_permissions)


def create_task_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    TodoItem = apps.get_model('todoBoard', 'TodoItem')
    # Create group
    task_permissions_group, _ = Group.objects.get_or_create(name='Task editors')

    # Fetch TodoList(board) content type
    task_content_type = ContentType.objects.get_for_model(TodoItem)

    # Add permissions
    task_permissions = Permission.objects.filter(content_type=task_content_type)

    task_permissions_group.permissions.add(*task_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0006_alter_todolist_allowed_groups'),
        ('auth', '0001_initial'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_board_group_permissions),
        migrations.RunPython(create_task_group_permissions),
    ]
