# Generated by Django 4.2.1 on 2024-01-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0007_fix_create_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': [('can_create_board', 'Allow user to create a board'), ('can_view_board', 'Allow user to view board'), ('can_delete_board', 'Allow user to delete board'), ('can_edit_board', 'Allow user to edit board details')]},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='due_to',
        ),
    ]
