# Generated by Django 4.2.1 on 2024-02-03 10:31

from django.db import migrations


def update_board_editors_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    TodoList = apps.get_model('todoBoard', 'TodoList')

    # Fetch TodoList(board) content type
    board_content_type = ContentType.objects.get_for_model(TodoList)

    # Create group
    group, _ = Group.objects.update_or_create(name='Board editors', defaults={'name': 'This app editors'})

    # Add permissions
    board_editor_permissions = Permission.objects.filter(content_type=board_content_type,
                                                         codename__in=['can_view_board', 'can_edit_board'])

    group.permissions.add(*board_editor_permissions)


def revert_board_editors_group(apps, schema_editor):
    # Just for test reasons
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='This app editors').update(name='Board editors')


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0008_alter_todolist_options_remove_todoitem_due_to'),
    ]

    operations = [
        migrations.RunPython(update_board_editors_group, revert_board_editors_group),
    ]
