# Generated by Django 4.2.1 on 2024-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0010_rename_category_todoitem_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
