# Generated by Django 4.2.1 on 2025-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0011_todolist_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started'), ('BL', 'Blocked'), ('PR', 'In Progress'), ('DN', 'Done')], default='NS', max_length=15),
        ),
    ]
