# Generated by Django 4.2.1 on 2025-06-08 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoBoard', '0012_alter_todoitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='todolist',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
