# Generated by Django 4.2.1 on 2025-06-15 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoBoard', '0014_set_todolist_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
