# Generated by Django 4.2.1 on 2025-06-15 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoBoard', '0015_alter_todolist_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
