# Generated by Django 4.2.1 on 2025-07-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoBoard', '0017_alter_todolist_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'permissions': [('create_task', 'Allow user to add task'), ('edit_task', 'Allow user to edit task details'), ('delete_task', 'Allow user to delete task')]},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': [('create_board', 'Allow user to create a board'), ('edit_board', 'Allow user to edit board details'), ('delete_board', 'Allow user to delete board')]},
        ),
    ]
